"""empty message

Revision ID: 2c550418ec1e
Revises: f5876887347d
Create Date: 2022-02-01 21:45:36.607573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c550418ec1e'
down_revision = 'f5876887347d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starships', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_column('starships', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starships', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('starships', 'name')
    # ### end Alembic commands ###
