"""empty message

Revision ID: db524d91eda5
Revises: d3e31759a115
Create Date: 2022-02-01 19:50:14.119518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db524d91eda5'
down_revision = 'd3e31759a115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favs__characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_user', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=80), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('starships', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('starships', 'model',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('starships', 'manufacturer',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('starships', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('starships', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starships', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.alter_column('starships', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starships', 'manufacturer',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('starships', 'model',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('starships', 'user_id')
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('favs__characters')
    # ### end Alembic commands ###
